Repository pulumi/pulumi-kubernetes, pull requests merged in 2024-03, with the labels that each got.

#2866 Update Pulumi to v3.109.0
  provider/go.mod
  provider/go.sum
  sdk/go.mod
  sdk/go.sum
  tests/go.mod
  tests/go.sum
Labels: impact/no-changelog-required, kind/task

#2873 yaml/v2: Detect file patterns automatically
  provider/pkg/provider/yaml/v2/yaml.go
  provider/pkg/provider/yaml/v2/yaml_test.go
Labels: impact/no-changelog-required

#2888 Refactor v2/yaml parsing code
  provider/pkg/host/fake/monitor.go
  provider/pkg/provider/yaml/v2/configfile.go
  provider/pkg/provider/yaml/v2/configgroup.go
  provider/pkg/provider/yaml/v2/yaml.go
  provider/pkg/provider/yaml/v2/yaml_test.go
  tests/gomega/matchers.go
  tests/pulumirpc/log.go
  tests/sdk/nodejs/helm_test.go
Labels: impact/no-changelog-required

#2891 Upgrade postgres operator integration test to use v1.11.0
  tests/sdk/nodejs/examples/helm-release-crd/step1/index.ts
  tests/sdk/nodejs/examples/helm-release-crd/step2/index.ts
Labels: impact/no-changelog-required

#2897 yaml/v2: apply the namespace uniformly to the resource name
  provider/pkg/clients/clients.go
  provider/pkg/clients/clients_test.go
  provider/pkg/provider/provider_construct.go
  provider/pkg/provider/resource/provider.go
  provider/pkg/provider/yaml/v2/configfile.go
  provider/pkg/provider/yaml/v2/configfile_test.go
  provider/pkg/provider/yaml/v2/configgroup.go
  provider/pkg/provider/yaml/v2/configgroup_test.go
  provider/pkg/provider/yaml/v2/yaml.go
  provider/pkg/provider/yaml/v2/yaml_test.go
Labels: impact/no-changelog-required

#2900 [yaml/v2] Improved resource prefix
  provider/pkg/provider/yaml/v2/configfile_test.go
  provider/pkg/provider/yaml/v2/configgroup_test.go
  provider/pkg/provider/yaml/v2/yaml.go
  provider/pkg/provider/yaml/v2/yaml_test.go
Labels: impact/no-changelog-required

#2901 Combined dependencies PR
  provider/go.mod
  provider/go.sum
  tests/go.mod
  tests/go.sum
Labels: impact/no-changelog-required, dependencies

#2904 Fix: Missing Kind in preview mode (yaml/v2)
  Makefile
  provider/pkg/clients/cache.go
  provider/pkg/clients/clients.go
  provider/pkg/clients/clients_test.go
  provider/pkg/provider/invoke_decode_yaml.go
  provider/pkg/provider/invoke_helm_template.go
  provider/pkg/provider/provider.go
  provider/pkg/provider/provider_configure_test.go
  provider/pkg/provider/resource/provider.go
  provider/pkg/provider/yaml/v2/yaml.go
  tests/provider/yamlv2/Pulumi.yaml
  tests/provider/yamlv2/crds.yaml
  tests/provider/yamlv2_test.go
Labels: area/yaml, impact/no-changelog-required

#2919 Pulumi/Pulumi upgrade to v3.112.0
  provider/cmd/pulumi-gen-kubernetes/main.go
  provider/go.mod
  provider/go.sum
  sdk/go.mod
  sdk/go.sum
  tests/go.mod
  tests/go.sum
Labels: impact/no-changelog-required
